name: Build-And-Deploy

on:
  push:
    branches:
      - main

jobs:
  build-app: 
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Specify the Node.js version you want to use

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Upload dist as artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./dist/

  build-image:
    needs: build-app
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download dist from artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: ./dist/

      - name: Log in to Private Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_URI }}
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      
      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with: 
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY_URI }}/portfolio-frontend:latest

  deploy-image:
    needs: build-image
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy docker-Compose.yml
        run: scp -o StrictHostKeyChecking=no ./docker/docker-compose.yml root@${{ secrets.SSH_IP }}:~/portfolio/frontend

      - name: Run docker-compose.yml
        run: ssh -o StrictHostKeyChecking=no root@${{ secrets.SSH_IP }} "cd ~/portfolio/frontend && docker-compose pull && docker-compose up -d"
