name: Docker-Build-And-Deploy

on:
  push:
    branches:
      - main

jobs:
  build-app:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Upload dist as artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./dist/

  build-image:
    needs: build-app
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download dist from artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: ./dist/

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with: 
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY_USER }}/portfolio-frontend:latest
    
  deploy-image:
    needs: build-image
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy docker-compose.yml
        run: cp ./docker/docker-compose.yml ~/deployment/portfolio/frontend

      - name: Run docker-compose.yml
        run: cd ~/deployment/portfolio/frontend && docker-compose pull && docker-compose up -d